cmds = {"help": ["get halp for doggo speak!", "Bork bork. I need ***help***!!", 1, "general"],
        "commands": ["detailed doggo-speak lessons", "Bork. What's all the ***commands*** you have??", 1, "general"],
        "calculate": ["nerd doggo calculates equation for you!", "Bork. Hey DogeyBot, ***what's*** 1 + 1?", 1, "utility"],
        "time": ["get the time. it's snacc time!", "Bork bork!! What's the ***time***?!", 1, "utility"],
        "meme": ["doggo memes. such funny", "Bork meme pls", 1, "fun"],
        "politic": ["r/politics posts", "bork bork i want some ***politics*** to make me rage", 1, "fun"],
        "news": ["get the news ~~about doggos~~", "bork bork doggo of the lake what ***news*** do you have?", 1, "fun"],
        "quote": ["get a quote", "bork bork booooored, i want a ***quote***", 1, "fun"],
        "balance": ["get ur dogecoin balance", "bork bork money money!!!!! whats me ***balance***", 1, "currency"],
        "inventory": ["see ur inventory", "bork whats in my inventory?!", 1, "currency"],
        "mine": ["mine for stuff. then sell it for dogecoin! such rich", "bork mine", 3, "currency"],
        "shop": ["shop for stuff. very nice!", "bork shop / bork shop [item] / bork shop [page]", 5, "currency"],
        "buy": ["buy stuff", "bork buy [item]", 5, "currency"],
        "sell": ["sell stuff", "bork sell [item] [quantity] / bork sell [item] all", 5, "currency"],
        "gift": ["gift stuff", "bork gift [person] [quantity] [item] / bork gift [item] all", 30*60, "currency"],
        "share": ["share your dogecoins. taxes are there, and limits too.", "bork share [person] [quantity] / bork share all", 90*60, "currency"],
        "steal": ["ugh i hate mining. i love rich. hey lets steal dogecoins", "bork steal [person]", 60*60*12, "currency"],
        "scout": ["i wamt rob but need prepare. hey let's scout his house. see person's best defense (will see vault if person has vault and safe)", "bork scout [person]", 60*5, "currency"],
        "rich": ["see who is richest", "bork who is richest??", 10, "currency"]}
categories = ["general", "utility", "fun", "currency"]
