cmds = {"help":["get halp for doggo speak!","Bork bork. I need ***help***!!",1],
        "commands":["detailed doggo-speak lessons","Bork. What's all the ***commands*** you have??",1],
        "calculate":["nerd doggo calculates equation for you!","Bork. Hey DogeyBot, ***what's*** 1 + 1?",1],
        "time":["get the time. it's snacc time!", "Bork bork!! What's the ***time***?!",1],
        "meme":["doggo memes. such funny", "Bork meme pls",1],
        "politic":["r/politics posts","bork bork i want some ***politics*** to make me rage",1],
        "news":["get the news ~~about doggos~~","bork bork doggo of the lake what ***news*** do you have?",1],
        "quote":["get a quote","bork bork booooored, i want a ***quote***",1],
        "balance":["get ur dogecoin balance","bork bork money money!!!!! whats me ***balance***",1],
        "inventory":["see ur inventory","bork whats in my inventory?!"]} 